// Generated by Wrangler
// by running `wrangler types --env-interface CloudflareEnv env.d.ts`

interface CloudflareEnv {
}

declare global {
    namespace NodeJS {
        interface ProcessEnv {
            // Add here the Cloudflare Bindings you want to have available in your application
            // (for more details on Bindings see: https://developers.cloudflare.com/pages/functions/bindings/)
            //
            // KV Example:
            // MY_KV: KVNamespace
            DB: D1Database;
        }
    }
}

export { }