compatibility_date = "2024-07-25"
compatibility_flags = ["nodejs_compat"]
name = "kanban"
pages_build_output_dir = ".vercel/output/static"

[[d1_databases]]
binding = "DB"
database_id = "903c66d2-41ad-495a-86b7-a32b2ba60d99"
database_name = "kanban-app-db"
migrations_dir = "drizzle/migrations"
preview_database_id = "DB"
